/*jshint node:true */
'use strict';

var bodyParser  	= require('body-parser');
var crypto      	= require('crypto');
var app         	= require('express')();
var jwt         	= require('jsonwebtoken');
var svgCaptcha  	= require('svg-captcha');
var algorithm 		= 'aes-256-ctr';
var SECRET      	= process.env.SECRET || "defaultSecret";
var SALT      		= process.env.SALT || "defaultSalt";
var PRIVATE_KEY 	= process.env.PRIVATE_KEY || "defaultPrivateKey";

app.use(bodyParser.json());

var args = process.argv;
if (args.length == 3 && args[2] == 'server') {
	var server = app.listen(3000, 'localhost', function () {
		var host = server.address().address;
		var port = server.address().port;
		console.log("MyGov Captcha Service listening at http://%s:%s", host, port);
	});
}

////////////////////////////////////////////////////////
/*
 * Encryption Routines
 */
////////////////////////////////////////////////////////
function decrypt(password, private_key) {
	try {
		if (!private_key) {
			private_key = PRIVATE_KEY;
		}
		var decipher = crypto.createDecipher(algorithm, private_key);
		var dec = decipher.update(password, 'hex', 'utf8');
		dec += decipher.final('utf8');
		return dec;
	} catch (e) {
		console.log("Error in cipher:", e);
		return "";
	}
}
function encrypt(password, private_key) {
	try {
		if (!private_key) {
			private_key = PRIVATE_KEY;
		}
		var cipher = crypto.createCipher(algorithm, private_key);
		var crypted = cipher.update(password, 'utf8', 'hex');
		crypted += cipher.final('hex');
		return crypted;
	} catch (e) {
		console.log("Error in cipher:", e);
		return "";
	}
}


////////////////////////////////////////////////////////
/*
 * Get a new captcha
 */
////////////////////////////////////////////////////////
var getCaptcha = function (payload) {
	// console.log("getCaptcha:", payload.nonce);
	var captcha = svgCaptcha.create();
	if (!captcha || (captcha && !captcha.data)) {
		// Something bad happened with Captcha.
		return {valid: false};
	}
	// Leaving this open until debugging finished.
	console.log("captcha generated:", captcha.text);
	var validation = encrypt(payload.nonce, SALT+captcha.text);
	if (validation === "") {
		// Error
		return {valid: false};
	} else {
		console.log("validation:", validation);
		return {nonce: payload.nonce, captcha: captcha.data, validation: validation};
	}
};
exports.getCaptcha = getCaptcha;

app.post('/captcha', function (req, res) {
	var captcha = getCaptcha(req.body);
	// console.log("returing:", captcha);

	return res.send(captcha);
});


////////////////////////////////////////////////////////
/*
 * Verify a captcha against it's encrypted response.
 * If successful, return a signed jwt by us.
 */
////////////////////////////////////////////////////////
var verifyCaptcha = function (payload) {
	// console.log("incoming payload:", payload);
	var encryptedAnswer = payload.encryptedAnswer;
	var answer = payload.answer;
	var nonce = payload.nonce;
	// console.log("encryptedAnswer:", encryptedAnswer);
	// console.log("answer:", answer);
	var validation = decrypt(encryptedAnswer, SALT+answer);
	// console.log("decrypted:", validation);
	if (validation == nonce) {
		// Passed the captcha test
		console.log("Captcha verified! Creating JWT.");
		var token = jwt.sign({nonce: nonce}, SECRET);
		return token;
	} else {
		console.log("Captcha answer invalid!");
		return {valid: false};
	}
};
exports.verifyCaptcha = verifyCaptcha;

app.post('/verify/captcha', function (req, res) {
	var ret = verifyCaptcha(req.body);
	return res.send(ret);
});


////////////////////////////////////////////////////////
/*
 * Verify a JWT generated by us.
 */
////////////////////////////////////////////////////////
var verifyJWT = function (token, nonce) {
	try {
		// Leaving this open until debugging finished.
		console.log("verifying:", token, " against: ", nonce);
		var decoded = jwt.verify(token, SECRET);
		// console.log("decoded:", decoded);
		if (decoded.nonce === nonce) {
			console.log("Valid!");
			return {valid: true};
		} else {
			console.log("Invalid!");
			return {valid: false};
		}
	} catch (e) {
		console.log("Token/ResourceID Verification Failed:");
		return {valid: false};
	}
};
exports.verifyJWT = verifyJWT;

app.post('/verify/jwt', function (req, res) {
	res.send(verifyJWT(req.body.token, req.body.nonce));
});